#NLP2_2 https://www.hackerrank.com/challenges/detect-the-domain-name/problem?isFullScreen=true
    
#Код для проверки

import re

n = int(input())

pat = re.compile(r'[^_]http[s]?:\/\/(?:www\.)?([\w\.-]+\.\w+)')

dom = set()

for i in range(n):
    inp = input()
    
    x = re.findall(pat,inp)
    x = set(x)
    for y in x:
        dom.add(y)
        
st = ''
for v,d in enumerate(sorted(list(dom))):
    if v+1 !=len(dom):
        st+=d +str(';')
    else:
        st+=d
print(st)

#NLP2_1 https://www.hackerrank.com/challenges/detect-the-email-addresses/problem?isFullScreen=true
    
n = int(input())

pat = re.compile(r'([\w\_\.]*@[\w\_\.]+\.\w+)')

dom = set()

for i in range(n):
    inp = input()
    
    x = re.findall(pat,inp)
    x = set(x)
    for y in x:
        dom.add(y)
        
st = ''
for v,d in enumerate(sorted(list(dom))):
    if v+1 !=len(dom):
        st+=d +str(';')
    else:
        st+=d
print(st)  

In [ ]:
#NLP2_3 (дз1): Реализовать stemming, lemmatization & BoW на следующем датасете: (Russian Toxic-abuse comments)

import pandas as pd

In [5]:
data = pd.read_csv('../input/file-56/labeled.csv',encoding="utf-8")

com = data.comment.str.replace('\n','').str.lower()

In [5]:
!pip install --upgrade nltk gensim bokeh umap-learn

!pip install rsmorphy_lemmatizer --upgrade

!pip install pymystem3 

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 20.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 73.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 36.7 MB/s eta 0:00:00:00:0100:01
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.0
    Uninstalling scipy-1.14.0:
      Successfully uninstalled scipy-1.14.0
  Attempting uninstall: nltk
    Found existing installation: nltk 3.2.4
    Uninstalling nltk-3.2.4:
      Successfully uninstalled nltk-3.2.4
  Attempting uninstall: bokeh
    Found existing installation: bokeh 3.4.3
    Uninstalling bokeh-3.4.3:
      Successfully uninstalled bokeh-3.4.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
geoviews 1.12.0 requires bokeh<3.5.0,

In [28]:
from nltk.tokenize import WordPunctTokenizer
from collections import Counter
#from nltk.stem import WordNetLemmatizer
#from nltk.stem import PorterStemmer
from nltk.stem.snowball import RussianStemmer
from nltk.downloader import download
from nltk.corpus import stopwords
from pymystem3 import Mystem
from string import punctuation

In [7]:
download("stopwords")

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [43]:
tokenizer = WordPunctTokenizer()

le = Mystem()

rs = RussianStemmer()

punc = list(punctuation)

In [9]:
def vectorize(tokens):
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector
def unique(sequence):
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]

stopword = stopwords.words("russian")

special_char=[",",":"," ",";",".","?","'",'...','..','-']


In [11]:
data_tok = [tokenizer.tokenize(line) for line in com]

In [16]:
data_tok_1 = data_tok[:200]

In [32]:
#Stemm
vocab = unique(rs.stem(word) for line in data_tok_1 for word in line) 

filtered_vocab = [word for word in vocab if word not in special_char and (word not in stopword or word not in punc)]

vector = [vectorize(line) for line in data_tok_1]

len(vocab), len(filtered_vocab)

(3122, 3115)

In [33]:
#Lemm
vocab = unique(le.lemmatize(word)[0] for line in data_tok_1 for word in line) 

filtered_vocab = [word for word in vocab if word not in special_char and (word not in stopword or word not in punc)]

vector = [vectorize(line) for line in data_tok_1]

len(vocab), len(filtered_vocab)

(3045, 3041)

In [44]:
#TF-IDF

#NLP2_4 Реализовать классификатор токсичных комментариев tfidf на базе датасета

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
test = com.to_list()

In [74]:
count = CountVectorizer(stop_words = stopword)

word_count = count.fit_transform(test)

print(word_count)

  (0, 7459)	1
  (0, 13497)	1
  (0, 5533)	1
  (1, 64911)	1
  (1, 67816)	1
  (1, 36748)	1
  (1, 19168)	1
  (1, 51692)	1
  (1, 29284)	1
  (1, 9051)	1
  (1, 64876)	2
  (1, 65150)	1
  (1, 22768)	1
  (1, 45809)	1
  (2, 55200)	1
  (2, 55212)	1
  (2, 54884)	1
  (3, 67816)	2
  (3, 57737)	1
  (3, 34122)	1
  (3, 13484)	2
  (3, 36184)	1
  (3, 14923)	1
  (3, 63319)	1
  (3, 29083)	1
  :	:
  (14410, 65675)	1
  (14410, 45426)	1
  (14410, 12202)	1
  (14411, 25308)	1
  (14411, 43557)	1
  (14411, 23959)	1
  (14411, 7940)	1
  (14411, 53949)	1
  (14411, 58822)	1
  (14411, 21955)	1
  (14411, 44472)	1
  (14411, 52982)	1
  (14411, 30390)	1
  (14411, 50750)	1
  (14411, 44492)	1
  (14411, 40082)	1
  (14411, 39409)	1
  (14411, 35948)	1
  (14411, 22424)	1
  (14411, 67069)	1
  (14411, 52790)	1
  (14411, 64960)	1
  (14411, 65018)	1
  (14411, 7494)	1
  (14411, 12060)	1


In [68]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [69]:
tfidf_transformer = TfidfTransformer()

tfidf_transformer.fit(word_count)

df_idf = pd.DataFrame(tfidf_transformer.idf_,index = count.get_feature_names_out(), columns = ['idf'])


In [70]:
df_idf.sort_values(by = ['idf'])

idf
это          2.575201
просто       3.728943
вообще       4.183969
очень        4.200861
всё          4.235527
...               ...
марсоход     9.882739
мартина      9.882739
мартини      9.882739
марксистско  9.882739
ётавских     9.882739

[68281 rows x 1 columns]

In [75]:
tf_idf_vector = tfidf_transformer.transform(word_count)

feauter_names = count.get_feature_names_out()

first_name = tf_idf_vector[50]

df_tfidf = pd.DataFrame(first_name.T.todense(), index = feauter_names, columns=['tfidf'])


df_tfidf.sort_values(by = ['tfidf'], ascending=False).iloc[:20]

tfidf
сожаленю     0.295054
исчезнут     0.295054
опускаться   0.295054
фашингтоном  0.295054
понятного    0.274359
пиндосам     0.257652
тупым        0.253665
мультики     0.250149
показывать   0.236958
пиндосы      0.234898
секунд       0.220866
поняли       0.214204
приходится   0.210467
уровня       0.195569
своим        0.190664
вместе       0.186062
сколько      0.153915
прибору      0.000000
прибором     0.000000
прибрежного  0.000000

In [15]:
from numpy.linalg import norm
from numpy import dot

In [81]:
tf_v = TfidfVectorizer(stop_words= stopword)

In [96]:
v_test = tf_v.fit_transform(test)

In [26]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

File './quora.txt' already there; not retrieving.


In [27]:
data1 = list(open('./quora.txt', encoding='utf-8'))

data1 = data1[:100]

In [28]:
tf_v_e = TfidfVectorizer()

tf_m = tf_v_e.fit_transform(data1)

In [29]:
size = len(tf_m.toarray())

arr = tf_m.toarray().tolist()

In [38]:
res = []
for i in range(size):
    for j in range(size):
        if arr[i] != arr[j]:
            cos = dot(arr[i], arr[j])/(norm(arr[i])*norm(arr[j]))
            res+=[[cos,data1[i],data1[j]]]

In [41]:
sorted(res, key = lambda x: x[0],reverse=True)[:1]

[[0.58622245199333,
  'What is your review of osquery?\n',
  'What is your review of iPad Mini 2?\n']]

In [40]:
pd.DataFrame(res)

0                                                  1  \
0     0.000000  Can I get back with my ex even though she is p...   
1     0.000000  Can I get back with my ex even though she is p...   
2     0.000000  Can I get back with my ex even though she is p...   
3     0.000000  Can I get back with my ex even though she is p...   
4     0.103211  Can I get back with my ex even though she is p...   
...        ...                                                ...   
9895  0.037619   What is the IUPAC name of tert-butyl chloride?\n   
9896  0.000000   What is the IUPAC name of tert-butyl chloride?\n   
9897  0.055134   What is the IUPAC name of tert-butyl chloride?\n   
9898  0.148139   What is the IUPAC name of tert-butyl chloride?\n   
9899  0.048225   What is the IUPAC name of tert-butyl chloride?\n   

                                                      2  
0     What are some ways to overcome a fast food add...  
1     Who were the great Chinese soldiers and leader...  
2                 What are ZIP codes in the Bay Area?\n  
3     Why was George RR Martin critical of JK Rowlin...  
4          What can I do to improve my immune system?\n  
...                                                 ...  
9895  Which was the best porn video you have ever se...  
9896                How can I get SBI transaction ID?\n  
9897  What is a good way to start studying for a car...  
9898              What are the components of fitness?\n  
9899  What is the good approach to implement rest AP...  

[9900 rows x 3 columns]